/**
 * Constants related to AI functionality for the writing enhancement interface.
 * This file defines various constants used throughout the application for
 * AI-powered writing improvement features.
 */

/**
 * Categories for organizing prompt templates in the sidebar
 */
export const PROMPT_CATEGORIES = {
  GENERAL: 'general',
  STYLE: 'style',
  TONE: 'tone',
  GRAMMAR: 'grammar',
  FORMAT: 'format'
};

/**
 * Interface for prompt template objects
 */
export interface PromptTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  promptText: string;
  isSystem: boolean;
  icon?: string;
}

/**
 * Predefined improvement templates available in the sidebar
 * These templates provide quick access to common improvement types
 */
export const DEFAULT_PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: 'make-shorter',
    name: 'Make it shorter',
    description: 'Condense the text while preserving key information',
    category: PROMPT_CATEGORIES.LENGTH,
    promptText: 'Rewrite the following text to be more concise while preserving all key information and maintaining the original tone:',
    isSystem: true,
    icon: 'compress'
  },
  {
    id: 'professional-tone',
    name: 'More professional tone',
    description: 'Adjust the tone to be more suitable for professional contexts',
    category: PROMPT_CATEGORIES.TONE,
    promptText: 'Rewrite the following text to have a more professional and formal tone while preserving the original meaning:',
    isSystem: true,
    icon: 'briefcase'
  },
  {
    id: 'improve-grammar',
    name: 'Improve grammar',
    description: 'Fix grammatical errors and improve sentence structure',
    category: PROMPT_CATEGORIES.GRAMMAR,
    promptText: 'Correct any grammatical errors, improve sentence structure, and enhance clarity in the following text:',
    isSystem: true,
    icon: 'check-grammar'
  },
  {
    id: 'simplify-language',
    name: 'Simplify language',
    description: 'Make the text easier to understand for a general audience',
    category: PROMPT_CATEGORIES.STYLE,
    promptText: 'Rewrite the following text to use simpler language and be more easily understood by a general audience:',
    isSystem: true,
    icon: 'simplify'
  },
  {
    id: 'add-examples',
    name: 'Add examples',
    description: 'Include relevant examples to clarify concepts',
    category: PROMPT_CATEGORIES.CONTENT,
    promptText: 'Add relevant examples to the following text to help clarify concepts and improve understanding:',
    isSystem: true,
    icon: 'example'
  },
  {
    id: 'academic-style',
    name: 'Academic style',
    description: 'Adjust the text to follow academic writing conventions',
    category: PROMPT_CATEGORIES.STYLE,
    promptText: 'Rewrite the following text to follow academic writing conventions, including appropriate citation placeholders if needed:',
    isSystem: true,
    icon: 'academic'
  },
  {
    id: 'creative-rewrite',
    name: 'Creative rewrite',
    description: 'Rewrite the text with more creative and engaging language',
    category: PROMPT_CATEGORIES.STYLE,
    promptText: 'Rewrite the following text to be more creative, engaging, and compelling while preserving the original meaning:',
    isSystem: true,
    icon: 'creative'
  },
  {
    id: 'bullet-points',
    name: 'Convert to bullet points',
    description: 'Transform paragraphs into organized bullet points',
    category: PROMPT_CATEGORIES.FORMAT,
    promptText: 'Convert the following text into well-organized bullet points that capture all key information:',
    isSystem: true,
    icon: 'list'
  },
  {
    id: 'casual-tone',
    name: 'More casual tone',
    description: 'Make the text sound more conversational and friendly',
    category: PROMPT_CATEGORIES.TONE,
    promptText: 'Rewrite the following text to have a more casual, conversational, and friendly tone:',
    isSystem: true,
    icon: 'chat'
  },
  {
    id: 'persuasive',
    name: 'More persuasive',
    description: 'Enhance the persuasive elements of the text',
    category: PROMPT_CATEGORIES.STYLE,
    promptText: 'Rewrite the following text to be more persuasive and compelling while maintaining credibility:',
    isSystem: true,
    icon: 'persuade'
  }
];

/**
 * Status values for tracking the state of AI suggestions
 */
export const SUGGESTION_STATUS = {
  PENDING: 'pending',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  ERROR: 'error'
};

/**
 * Types of suggestions that can be generated by the AI
 */
export const SUGGESTION_TYPES = {
  GRAMMAR: 'grammar',
  STYLE: 'style',
  TONE: 'tone',
  LENGTH: 'length',
  CLARITY: 'clarity',
  FORMAT: 'format'
};

/**
 * Possible decisions for each suggested change in track changes view
 */
export const CHANGE_DECISION = {
  ACCEPT: 'accept',
  REJECT: 'reject',
  PENDING: 'pending'
};

/**
 * Role identifiers for messages in the chat interface
 */
export const MESSAGE_ROLES = {
  USER: 'user',
  ASSISTANT: 'assistant',
  SYSTEM: 'system'
};

/**
 * Standard error messages for AI processing issues
 */
export const AI_ERROR_MESSAGES = {
  GENERAL_ERROR: 'An error occurred while processing your request. Please try again.',
  TIMEOUT_ERROR: 'The request took too long to process. Please try again or use a shorter text selection.',
  RATE_LIMIT_ERROR: 'You have reached the maximum number of requests. Please try again later or upgrade your account.',
  CONTENT_POLICY_ERROR: 'Your request could not be processed due to content policy restrictions. Please revise your text or prompt.'
};

/**
 * Maximum token limits for different parts of the application
 * Based on typical limits for large language models like GPT-4
 */
export const MAX_TOKEN_LIMITS = {
  DOCUMENT: 25000, // Maximum document size in tokens
  CHAT_MESSAGE: 4000, // Maximum size of a single chat message
  CONTEXT_WINDOW: 8000 // Maximum context window for AI processing
};

/**
 * State indicators for AI processing status in the UI
 */
export const AI_PROCESSING_STATES = {
  IDLE: 'idle',
  REQUESTING: 'requesting',
  PROCESSING: 'processing',
  COMPLETED: 'completed',
  ERROR: 'error'
};

/**
 * Timeout duration in milliseconds for AI requests
 * 30 seconds default timeout
 */
export const AI_REQUEST_TIMEOUT = 30000;