# This file defines Secret resources for storing sensitive configuration data
# used by the AI writing enhancement application. This base file contains template
# secrets that will be populated with actual values by environment-specific overlays.
#
# NOTE: Do not store actual secret values in this file. Use kustomize secretGenerator
# or sealed-secrets to manage actual values in environment-specific overlays.

---
# MongoDB database credentials for document storage
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  MONGODB_URI: placeholder
  MONGODB_USERNAME: placeholder
  MONGODB_PASSWORD: placeholder
  MONGODB_DATABASE: placeholder
---
# Redis credentials for caching and session management
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
type: Opaque
data:
  REDIS_HOST: placeholder
  REDIS_PORT: placeholder
  REDIS_PASSWORD: placeholder
---
# AWS S3 credentials for document backup storage
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: placeholder
  AWS_SECRET_ACCESS_KEY: placeholder
  S3_BUCKET_NAME: placeholder
  S3_REGION: placeholder
---
# OpenAI API credentials for AI suggestion and chat features
apiVersion: v1
kind: Secret
metadata:
  name: openai-credentials
type: Opaque
data:
  OPENAI_API_KEY: placeholder
  OPENAI_ORGANIZATION: placeholder
---
# JWT signing keys and configuration for user authentication
apiVersion: v1
kind: Secret
metadata:
  name: auth-credentials
type: Opaque
data:
  JWT_SECRET_KEY: placeholder
  JWT_REFRESH_SECRET_KEY: placeholder
  JWT_ACCESS_TOKEN_EXPIRES: placeholder
  JWT_REFRESH_TOKEN_EXPIRES: placeholder
---
# Auth0 credentials for optional external authentication
apiVersion: v1
kind: Secret
metadata:
  name: auth0-credentials
type: Opaque
data:
  AUTH0_DOMAIN: placeholder
  AUTH0_CLIENT_ID: placeholder
  AUTH0_CLIENT_SECRET: placeholder
  AUTH0_AUDIENCE: placeholder
---
# Email service credentials for user notifications and verification
apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
type: Opaque
data:
  EMAIL_SERVICE_API_KEY: placeholder
  EMAIL_FROM_ADDRESS: placeholder
  EMAIL_SERVICE_PROVIDER: placeholder
---
# Application-level secrets for session management and data encryption
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  FLASK_SECRET_KEY: placeholder
  ENCRYPTION_KEY: placeholder